### ISSUE TITLE
GHC-8.4.x support (in Hackage)

### ISSUE THREAD

**Issue by yairchu** [thsutton/aeson-diff#43]
The `master` branch already supports GHC-8.4.x but these changes weren't uploaded to hackage.
It would be nice to be able to use `aeson-diff` in cabal based builds or in stack based builds without extra `stack.yaml` chants :)

**Comment by thsutton** [comment]
Sorry. Doing a release right now.

**Comment by thsutton** [comment]
[Done](https://hackage.haskell.org/package/aeson-diff-1.1.0.5). Thanks for poking me!
