### ISSUE TITLE
Does not respect RFC remove specification

### ISSUE THREAD

**Issue by samtay** [thsutton/aeson-diff#47]
Removing keys whose values are arrays is broken. Example:
```json
# original json
{ "foo": ["bar"], "baz": "quux"}

# patch
{ "op": "remove", "path": "/foo" }

# resulting json
{ "foo": ["bar"], "baz": "quux"}
```
This also breaks things that depend on `remove`, such as `replace`.

**Comment by samtay** [comment]
False alarm, sorry!

**Comment by thsutton** [comment]
No worries. If you can think of any additional test cases or documentation changes, please open an issue!
