### ISSUE TITLE
Bump dependencies for current LTS

### ISSUE THREAD

**Issue by thsutton** [thsutton/aeson-diff#50]
https://github.com/kuribas/aeson-diff-generic/pull/2#issuecomment-531087612

**Comment by sshine** [comment]
Hi @thsutton. I meant to send a PR for `aeson-diff`, too, but ran short on time.

Let me know if you have a bump scheduled, or if you'd like a PR.

**Comment by thsutton** [comment]
@sshine A PR would be very welcome. Thanks for offering!
