### ISSUE TITLE
Library needs a base bump for ghc 9.0.1

### ISSUE THREAD

**Issue by archaeron** [thsutton/aeson-diff#59]
I wanted to use the library with ghc 9.0.1 but it's not working because of the requirement for base < 4.16

I added `allow-newer: true` to my stack.yaml file and it seems to work. 
I believe just increasing the version number would be enough :)

thank you!

**Comment by thsutton** [comment]
Release uploaded. Sorry for the looong delay.

**Comment by archaeron** [comment]
thank you :)
