### ISSUE TITLE
Should the ToJSON instance for your Patch use rfc6902?

### ISSUE THREAD

**Issue by christian-marie** [thsutton/aeson-diff#8]
I was thinking of using this to build a proper PATCH update abstraction for servant, but standards are nice, right.

Do you think that Patch should encode like this? http://tools.ietf.org/html/rfc6902

**Comment by thsutton** [comment]
That does seem like a good idea. Are you planning to implement this or would you like me to?

**Comment by thsutton** [comment]
> numbers: are considered equal if their values are numerically equal.

This spec is already feeling very, very Javascript-y.

**Comment by christian-marie** [comment]
On Tue, Jan 19, 2016 at 11:48:41PM -0800, Thomas Sutton wrote:

> That does seem like a good idea. Are you planning to implement this or would
> you like me to?
> 
> . . .
> 
> > numbers: are considered equal if their values are numerically equal.
> 
> This spec is already feeling very, very Javascript-y.

JSON is an awesome binary serialisation format. I feel that MessagePack, whilst
it makes interesting points in introducing "types" and being a regular language
(parse ["5]"]), is way off-base in optimising for speed, simplicity, sanity and
size.

The world needs more enormously wasteful and convoluted things, and JSON is
perfect for this cause; JSON is a great success story -- truly an achiever in
its own special way. JavaScript may have been a cute (although a tad premature)
baby, but it won't be around forever. JSON is JavaScript's eternal legacy, and
this specification is an expression of JavaScripts eternal love, whether you like
it or not.

Futhermore, I'm happy to implement the spec.

**Comment by thsutton** [comment]
I opened a branch but didn't push anything. Do you want to PR or to contributor on this repo?

**Comment by christian-marie** [comment]
I choose to contributor.

**Comment by thsutton** [comment]
collaborator away.

PS: I just noticed your github avatar. It's a remarkable resemblance.

**Comment by thsutton** [comment]
I'm about to merge PR #9 which replaces my ad hoc format with RFC 6902 support.

**Comment by christian-marie** [comment]
An excellent collaboration, thank you for your contributions to my feature.

**Comment by thsutton** [comment]
Trying to get it to work on LTS-2, LTS-3, LTS-5. Then I'll land it.

**Comment by christian-marie** [comment]
![90f7542493eb1216f54fd3200dfe03c7da2161f9](https://cloud.githubusercontent.com/assets/3360007/14337831/b8865e1a-fcb4-11e5-8607-3dfbe1453185.jpeg)
